https://stepik.org/lesson/1576168/step/5

**Подвиг 3**. Пусть дана следующая модель двухслойной нейронной сети:

<img src='https://ucarecdn.com/acf02b7c-7bfa-406b-bc11-19d6e09ca296/' width=500>

Ее весовые коэффициенты следует определить следующими тензорами:
```
W1 = torch.tensor([(w11, w12), (w21, w22)], dtype=torch.float32)
bias1 = torch.tensor([w10, w20], dtype=torch.float32)
W2 = torch.tensor([w1, w2], dtype=torch.float32)
bias2 = torch.tensor([w0], dtype=torch.float32)
```
Здесь `W1`, `bias1` - весовые коэффициенты первого слоя; `W2`, `bias2` - весовые коэффициенты второго (выходного) слоя.

Набор (мини-батч) входных данных задается тензором:
```
batch_size = 16 # количество входных данных
X = torch.tensor(list(map(float, input().split())), dtype=torch.float32).view(batch_size, 2)
```
Работу модели нейронной сети, изображенной на рисунке, можно описать векторно-матричными операциями следующим образом:

$$ h = σ(X ⋅ W1^T + bias1) $$
$$ y = u(h ⋅ W2^T + bias2) $$

где $σ()$ и $u()$ - функции активации для нейронов скрытого и выходного слоя соответственно.

Необходимо подобрать такие значения весовых коэффициентов и определить функции активации нейронной сети, чтобы выходное значение формировалось согласно выражению: $ y = 3 ⋅ x_1^2 - 2 ⋅ (x_1 + 0.5 ⋅ x_2)^2 +7.8 $

Вычислите выходные значения для тензора `X` и сохраните результат в одномерном тензоре predict длиной `batch_size`.

Замечание: в текущей версии PyTorch транспонирование матриц выполняется не с помощью свойства `t.mT`, а с помощью метода `t.transpose()` следующим образом:
```
WT = W.transpose(1,0) # меняет строки на столбцы
```
P.S. На экран ничего выводить не нужно.

Тесты: https://github.com/selfedu-rus/neuro-pytorch/blob/main/tests/1.11.3

In [ ]:
import torch


# тензор X в программе не менять
batch_size = 16 # количество входных данных
X = torch.tensor(list(map(float, input().split())), dtype=torch.float32).view(batch_size, 2)

# Коэффициенты берём из уравнения y=3⋅x_1^2​−2⋅(x_1​+0.5⋅x_2​)^2+7.8
w11, w12, w21, w22 = 1.0, 0.0, 1.0, .5
w10, w20 = .0, .0
w1, w2 = 3.0, -2.0
w0 = 7.8

# А функции активации (тоже из уравнения) будут
act_sigma = lambda z: z**2
act_u = lambda z: z

# Собираем коэффициенты в тензоры (матрицы и векторы)
W1 = torch.tensor([(w11, w12), (w21, w22)], dtype=torch.float32)
bias1 = torch.tensor([w10, w20], dtype=torch.float32)
W2 = torch.tensor([w1, w2], dtype=torch.float32)
bias2 = torch.tensor([w0], dtype=torch.float32)

# Векторно-матричные операции (по тексту задания)
h = act_sigma(X @ W1.transpose(1,0) + bias1)
y = act_u(h @ W2 + bias2)

predict = y
# predict

1.5 12.0 9.0 -10.5 0.0 0.0 13.5 -1.5 15.0 6.0 -6.0 0.0 -3.0 0.0 1.5 -3.0 4.5 -13.5 0.0 -6.0 -6.0 -12.0 4.5 1.5 6.0 1.5 6.0 -13.5 10.5 3.0 -10.5 -6.0


tensor([ -97.9500,  222.6750,    7.8000,  229.4250,   34.8000,   43.8000,
          16.8000,   14.5500,   58.4250,  -10.2000, -172.2000,   13.4250,
          24.6750,  114.6750,   50.5500,  -25.9500])

In [ ]:
# поставить на попа:
W2, W2.reshape(2,1)

(tensor([ 3., -2.]),
 tensor([[ 3.],
         [-2.]]))

```
test #1
input: 9.0 -4.5 13.5 4.5 15.0 -15.0 -10.5 -10.5 -3.0 7.5 -4.5 15.0 -3.0 9.0 -1.5 -4.5 -15.0 3.0 -13.5 -7.5 -10.5 -1.5 -10.5 6.0 10.5 9.0 -10.5 -15.0 -15.0 -7.5 -7.5 13.5
output:

test #2
input: 1.5 12.0 9.0 -10.5 0.0 0.0 13.5 -1.5 15.0 6.0 -6.0 0.0 -3.0 0.0 1.5 -3.0 4.5 -13.5 0.0 -6.0 -6.0 -12.0 4.5 1.5 6.0 1.5 6.0 -13.5 10.5 3.0 -10.5 -6.0
output:
```