https://stepik.org/lesson/1576168/step/6

https://machinelearningknowledge.ai/creating-ones-tensor-in-pytorch-with-torch-ones-and-torch-ones_like/

**Подвиг 4 (аналог подвига 3)**. Пусть дана следующая модель двухслойной нейронной сети:

<img src='https://ucarecdn.com/9c23bf28-3594-4ca5-9be7-2e4ed8f5dc59/' width=500>

Ее весовые коэффициенты следует определить следующими тензорами:
```
W1 = torch.tensor([(w11, w12), (w21, w22)], dtype=torch.float32)
bias1 = torch.tensor([w10, w20], dtype=torch.float32)
W2 = torch.tensor([w1, w2], dtype=torch.float32)
bias2 = torch.tensor([w0], dtype=torch.float32)
```
Здесь `W1`, `bias1` - весовые коэффициенты первого слоя; `W2`, `bias2` - весовые коэффициенты второго (выходного) слоя.

Набор (мини-батч) входных данных задается тензором:
```
batch_size = 16 # количество входных данных
X = torch.tensor(list(map(float, input().split())), dtype=torch.float32).view(batch_size, 2)
```
Работу модели нейронной сети, изображенной на рисунке, можно описать векторно-матричными операциями следующим образом:

$$ h = σ(X ⋅ W1^T + bias1) $$
$$ y = u(h ⋅ W2^T + bias2) $$

где $σ()$ и $u()$ - функции активации для нейронов скрытого и выходного слоя соответственно.

Необходимо подобрать такие значения весовых коэффициентов и определить функции активации нейронной сети, чтобы выходное значение формировалось согласно выражению:
$$
out=2⋅sin((0.5⋅x_1+0.5⋅x_2)⋅π+1.5)-3.5⋅sin(0.1⋅x_2-1.5π)
$$

$$
y=
\begin{cases}
1 & out≥0.5\\
-1 & out<0.5
\end{cases}
$$

Значение $π$ хранится в переменной `torch.pi`. Вычислите выходные значения для тензора `X` и сохраните результат в одномерном тензоре `predict` длиной `batch_size`.

Замечание: в текущей версии PyTorch транспонирование матриц выполняется не с помощью свойства t.mT, а с помощью метода t.transpose() следующим образом:

WT = W.transpose(1,0) # меняет строки на столбцы
P.S. На экран ничего выводить не нужно.

Тесты: https://github.com/selfedu-rus/neuro-pytorch/blob/main/tests/1.11.4

In [ ]:
import torch


# тензор X в программе не менять
batch_size = 16 # количество входных данных
X = torch.tensor(list(map(float, input().split())), dtype=torch.float32).view(batch_size, 2)

# Коэффициенты берём из формулы out=2⋅sin((0.5⋅x1+0.5⋅x2)⋅π+1.5)−3.5⋅sin(0.1⋅x2−1.5π)
w11, w12, w21, w22 = .5 * torch.pi, .5 * torch.pi, .0, .1 # веса первого слоя
w10, w20 = 1.5, -1.5 * torch.pi # смещения первого слоя
w1, w2 = 2.0, -3.5              # веса второго слоя
w0 = .0                         # смещение второго слоя

# А функции активации (тоже из формулы) будут
act_sigma = lambda z: torch.sin(z)
act_u = lambda out: torch.where(out >= 0.5, torch.ones_like(out), -torch.ones_like(out))

# Собираем коэффициенты в тензоры (матрицы и векторы)
W1 = torch.tensor([(w11, w12), (w21, w22)], dtype=torch.float32)
bias1 = torch.tensor([w10, w20], dtype=torch.float32)
W2 = torch.tensor([w1, w2], dtype=torch.float32)
bias2 = torch.tensor([w0], dtype=torch.float32)

# Векторно-матричные операции (по тексту задания)
h = act_sigma(X @ W1.transpose(1,0) + bias1)
y = act_u(h @ W2 + bias2)

predict = y
# predict

7.5 25.0 -25.0 17.5 -20.0 -22.5 -2.5 10.0 -15.0 -17.5 -15.0 -12.5 2.5 15.0 -7.5 2.5 10.0 10.0 10.0 17.5 -25.0 7.5 -12.5 -5.0 -10.0 12.5 2.5 22.5 12.5 -25.0 17.5 20.0


tensor([ 1.,  1.,  1., -1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1.,  1.,
         1., -1.])

In [ ]:
# поставить на попа:
W2, W2.reshape(2,1)

(tensor([ 3., -2.]),
 tensor([[ 3.],
         [-2.]]))

```
test #1
input: 9.0 -4.5 13.5 4.5 15.0 -15.0 -10.5 -10.5 -3.0 7.5 -4.5 15.0 -3.0 9.0 -1.5 -4.5 -15.0 3.0 -13.5 -7.5 -10.5 -1.5 -10.5 6.0 10.5 9.0 -10.5 -15.0 -15.0 -7.5 -7.5 13.5
output:

test #2
input: 1.5 12.0 9.0 -10.5 0.0 0.0 13.5 -1.5 15.0 6.0 -6.0 0.0 -3.0 0.0 1.5 -3.0 4.5 -13.5 0.0 -6.0 -6.0 -12.0 4.5 1.5 6.0 1.5 6.0 -13.5 10.5 3.0 -10.5 -6.0
output:
```