https://stepik.org/lesson/1576165/step/4

`Подвиг 2`. Продолжите программу, в которой сформированы два тензора `targets` и `t_onehot` следующим образом:
```
lst = list(map(int, input().split()))

targets = torch.tensor(lst, dtype=torch.int64)
t_onehot = torch.eye(targets.max()+1)[targets]
```
На основе тензора `t_onehot` необходимо сформировать еще один тензор `t_bags` путем суммирования строк тензора `t_onehot`. Например:
```
t_onehot:
tensor([[0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0.]])

t_bags:
tensor([0., 0., 2., 2., 0., 1.])
```
Затем, в тензоре `t_bags` определите индекс первого встреченного максимального значения и сохраните в переменной `pred`. Переменная `pred` должна ссылаться на число, а не на тензор с числом.

P.S. На экран ничего выводить не нужно.

Тесты: https://github.com/selfedu-rus/neuro-pytorch/blob/main/tests/1.8.2

In [ ]:
import torch

lst = list(map(int, input().split()))

targets = torch.tensor(lst, dtype=torch.int64)
t_onehot = torch.eye(targets.max()+1)[targets]

t_bags = t_onehot.sum(dim=0)
pred = torch.argmax(t_bags).item()

# print(t_onehot)
# print(t_bags)
# print(pred)

0 0 1 1 2 2 2
tensor([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])
tensor([2., 2., 3.])
2


```
test #1
input: 5 4 7 3 2
output:

test #2
input: 3 2 1 2 2 2 2 2 2
output:

test #3
input: 0 0 1 1 2 2 2
output:

test #4
input: 0
output:
```