https://stepik.org/lesson/1576162/step/3

In [ ]:
# Подвиг 1. Создайте в программе следующие тензоры с типом данных torch.int8:
import torch

# t1: размером (4, 8, 2), состоящий из всех нулей;
t1 = torch.zeros(4, 8, 2, dtype=torch.int8)

# t2: размером (1, 9), состоящий из всех единиц;
t2 = torch.ones(1, 9, dtype=torch.int8)

# t3: размером (5, 4), с единицами по главной диагонали и нулями в остальных элементах;
t3 = torch.eye(5, 4, dtype=torch.int8)

# t4: размером (2, 7, 1, 5), содержащий значения -5 во всех элементах.
t4 = torch.full((2, 7, 1, 5), -5, dtype=torch.int8) # Use torch.full t


display(t1)
display(t2)
display(t3)
display(t4)

tensor([[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]], dtype=torch.int8)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.int8)

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]], dtype=torch.int8)

tensor([[[[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]]],


        [[[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]],

         [[-5, -5, -5, -5, -5]]]], dtype=torch.int8)