https://stepik.org/lesson/1576172/step/7

Тесты: https://github.com/selfedu-rus/neuro-pytorch/blob/main/tests/2.4.5

In [ ]:
import torch

g = float(input()) # значение g в программе не менять
d = float(input()) # значение d в программе не менять

t = torch.tensor([d], requires_grad=True)

f = -g * t**2 / 2 + g * torch.exp(-t) + 1.5
f.backward()

# print(f)
# print(t.data, t.grad)

# tensor([-683.9825], grad_fn=<AddBackward0>)
# tensor([12.7000]) tensor([-107.9500])

tensor([-683.9825], grad_fn=<AddBackward0>)
tensor([12.7000]) tensor([-107.9500])


```
test #1
input:
8.5
12.7
output:

test #2
input:
10.1
5.7
output:

test #3
input:
12.5
34.2
output:
```