https://stepik.org/lesson/1576204/step/9

In [ ]:
import torch
import torch.nn as nn


class TwoLayerModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(3, 2)
        self.layer2 = nn.Linear(2, 1)

    def forward(self, x):
        return self.layer2(self.layer1(x).sigmoid())


x = torch.rand(3) # тензор x в программе не менять

model = TwoLayerModel()
model.eval()
predict = model(x)
predict

tensor([0.1487], grad_fn=<ViewBackward0>)

In [ ]:
import torch
import torch.nn as nn

class TwoLayerModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(8, 8)
        self.layer2 = nn.Linear(2, 1)

    def forward(self, x):
        x_input = torch.cat([x, torch.tensor([1]), x, torch.tensor([1])])
        h = self.layer1(x_input)
        h1 = x[0:3].sum().sigmoid()
        h2 = x[3:6].sum().sigmoid()
        return self.layer2(torch.tensor([h1, h2])).sigmoid()

x = torch.rand(3) # тензор x в программе не менять

model = TwoLayerModel()
model.eval()
predict = model(x)
predict

tensor([0.4481], grad_fn=<SigmoidBackward0>)

In [ ]:
x_input = torch.cat([x, torch.tensor([1]), x, torch.tensor([1])])
x_input

tensor([0.0925, 0.8229, 0.2466, 1.0000, 0.0925, 0.8229, 0.2466, 1.0000])