https://stepik.org/lesson/1576179/step/10

In [ ]:
import torch
import torch.nn as nn
import torchvision.transforms as tfs

class ToDtypeV1:
    def __init__(self, dtype=torch.float32, scale=False):
        self.dtype = dtype
        self.scale = scale

    def __call__(self, img):
        img = img.to(self.dtype)  # преобразование в заданный формат

        # # Масштабирование с "контрастностью"
        if self.scale and self.dtype in (torch.float16, torch.float32, torch.float64):
            img = (img - img.min()) / img.max()

        # Масштабирование с простым переносом из диапазона [0, 1] в диапазоне [0, 255]
        # if self.scale and self.dtype in (torch.float16, torch.float32, torch.float64):
        #     img = img / 255.0

        return img

# Исходное изображение
H, W = 128, 128
img_orig = torch.randint(0, 256, size=(3, H, W), dtype=torch.uint8) # тензор в программе не менять

# Расчет средних и отклонений
img_mean = img_orig.float().mean(dim=(1, 2))  # средние для каждого цветового канала (первая ось)
img_std = img_orig.float().std(dim=1, unbiased=False).mean(dim=1)    # отклонение для каждого цветового канала (первая ось)

# Функция для группы преобразований
to_tensor = tfs.Compose([ToDtypeV1(dtype=torch.float32, scale=False),
                         tfs.Normalize(mean=img_mean, std=img_std)])

# Применение группы преобразований
img = to_tensor(img_orig)

# # Проверка
# print("Форма преобразованного изображения:")
# print(img.shape)
# print("Средние (первая ось):")
# print(img_mean)
# print("Отклонения (первая ось):")
# print(img_std)


Форма преобразованного изображения:
torch.Size([3, 128, 128])
Средние (первая ось):
tensor([127.5753, 127.1597, 128.2852])
Отклонения (первая ось):
tensor([73.0897, 73.1175, 73.6554])


In [ ]:
import torch
import torch.nn as nn
import torchvision.transforms as tfs
# import torchvision.transforms.v2 as tfs_v2 - недоступен на Stepik

class ToDtypeV1(nn.Module):
    def __init__(self, dtype, scale=False):
        super().__init__()
        self.dtype = dtype
        self.scale = scale

    def forward(self, item):
        item = item.to(self.dtype)
        if self.scale and self.dtype in (torch.float16, torch.float32, torch.float64):
            item_min = item.min()
            item_max = item.max()
            item = (item - item_min) / item_max

        return item


H, W = 128, 128
img_orig = torch.randint(0, 256, size=(3, H, W), dtype=torch.uint8) # тензор в программе не менять

img_mean = torch.mean(img_orig.float(), [1, 2])
img_std = torch.std(img_orig.float().flatten(1, 2), dim=1)
transforms = tfs.Compose([ToDtypeV1(dtype=torch.float32, scale=False),
                          tfs.Normalize(mean=img_mean, std=img_std)
                          ])

img = transforms(img_orig)

# # Проверка
print("Преобразованное изображение:")
print(img_transform.shape)
print("Средние (первая ось):")
print(img_mean)
print("Отклонения (первая ось):")
print(img_std)

Преобразованное изображение:
torch.Size([3, 128, 128])
Средние (первая ось):
tensor([127.3781, 126.5436, 127.8182])
Отклонения (первая ось):
tensor([73.7543, 73.9360, 74.1318])
